package com.jinyan.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("data_dictionary", "id", DataDictionary.class);
		arp.addMapping("data_dictionary_value", "id", DataDictionaryValue.class);
		arp.addMapping("data_source", "id", DataSource.class);
		arp.addMapping("file_uploaded", "id", FileUploaded.class);
		arp.addMapping("form_sql", "id", FormSql.class);
		arp.addMapping("form_view", "id", FormView.class);
		arp.addMapping("gd_account", "id", Account.class);
		// Composite Primary Key order: accountId,roleId
		arp.addMapping("gd_account_role", "accountId,roleId", AccountRole.class);
		arp.addMapping("gd_ebooking_price", "id", EbookingPrice.class);
		arp.addMapping("gd_ebooking_price_plan", "id", EbookingPricePlan.class);
		arp.addMapping("gd_ebooking_room_stock", "id", EbookingRoomStock.class);
		arp.addMapping("gd_ebooking_room_type", "id", EbookingRoomType.class);
		arp.addMapping("gd_exclude_room", "id", ExcludeRoom.class);
		arp.addMapping("gd_hotel", "id", Hotel.class);
		arp.addMapping("gd_hotelquyu_gd_rooms", "id", HotelquyuGdRooms.class);
		arp.addMapping("gd_hotelroom_chg", "id", HotelroomChg.class);
		arp.addMapping("gd_hotelview", "id", Hotelview.class);
		arp.addMapping("gd_login_log", "id", LoginLog.class);
		arp.addMapping("gd_order", "id", Order.class);
		arp.addMapping("gd_order_change", "CpOrderID", OrderChange.class);
		arp.addMapping("gd_permission", "id", Permission.class);
		arp.addMapping("gd_pic", "id", Pic.class);
		arp.addMapping("gd_reissueInvoice", "id", ReissueInvoice.class);
		arp.addMapping("gd_role", "id", Role.class);
		// Composite Primary Key order: permissionId,roleId
		arp.addMapping("gd_role_permission", "permissionId,roleId", RolePermission.class);
		arp.addMapping("gd_room", "id", Room.class);
		arp.addMapping("gd_session", "id", Session.class);
		arp.addMapping("gd_store", "id", Store.class);
		arp.addMapping("gd_unused_hotel", "id", UnusedHotel.class);
		arp.addMapping("gd_unused_room", "id", UnusedRoom.class);
		//arp.addMapping("session", "id", Session.class);
		arp.addMapping("sys_function", "id", SysFunction.class);
		arp.addMapping("sys_log", "id", SysLog.class);
		arp.addMapping("sys_org", "id", SysOrg.class);
		arp.addMapping("sys_role", "id", SysRole.class);
		arp.addMapping("sys_role_function", "id", SysRoleFunction.class);
		arp.addMapping("sys_tree", "id", SysTree.class);
		arp.addMapping("sys_user", "id", SysUser.class);
		arp.addMapping("sys_user_role", "id", SysUserRole.class);
		arp.addMapping("w_sys_tree", "id", WSysTree.class);
	}
}


