package com.jinyan.model;

import com.jinyan.model.base.BaseAccountRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccountRole extends BaseAccountRole<AccountRole> {
	
}

