package com.jinyan.model;

import com.jinyan.model.base.BaseDataDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataDictionary extends BaseDataDictionary<DataDictionary> {
	
}

