package com.jinyan.model;

import com.jinyan.model.base.BaseDataDictionaryValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataDictionaryValue extends BaseDataDictionaryValue<DataDictionaryValue> {
	
}

