package com.jinyan.model;

import com.jinyan.model.base.BaseEbookingPricePlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EbookingPricePlan extends BaseEbookingPricePlan<EbookingPricePlan> {
	
}

