package com.jinyan.model;

import com.jinyan.model.base.BaseEbookingRoomStock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EbookingRoomStock extends BaseEbookingRoomStock<EbookingRoomStock> {
	
}

