package com.jinyan.model;

import com.jinyan.model.base.BaseEbookingRoomType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EbookingRoomType extends BaseEbookingRoomType<EbookingRoomType> {
	
}

