package com.jinyan.model;

import com.jinyan.model.base.BaseEbookingPrice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EbookingPrice extends BaseEbookingPrice<EbookingPrice> {
	
}

