package com.jinyan.model;

import com.jinyan.model.base.BaseExcludeRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExcludeRoom extends BaseExcludeRoom<ExcludeRoom> {
	
}

