package com.jinyan.model;

import com.jinyan.model.base.BaseFileUploaded;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FileUploaded extends BaseFileUploaded<FileUploaded> {
	
}

