package com.jinyan.model;

import com.jinyan.model.base.BaseHotelquyuGdRooms;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HotelquyuGdRooms extends BaseHotelquyuGdRooms<HotelquyuGdRooms> {
	
}

