package com.jinyan.model;

import com.jinyan.model.base.BaseHotelroomChg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HotelroomChg extends BaseHotelroomChg<HotelroomChg> {
	
}

