package com.jinyan.model;

import com.jinyan.model.base.BaseHotel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Hotel extends BaseHotel<Hotel> {
	
	//public Hotel dao=new Hotel().dao();
}

