package com.jinyan.model;

import com.jinyan.model.base.BaseLcCtripHotelPriceLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LcCtripHotelPriceLog extends BaseLcCtripHotelPriceLog<LcCtripHotelPriceLog> {
	
}

