package com.jinyan.model;

import com.jinyan.model.base.BaseOrderChange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderChange extends BaseOrderChange<OrderChange> {
	
}

