package com.jinyan.model;

import com.jinyan.model.base.BaseReissueInvoice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReissueInvoice extends BaseReissueInvoice<ReissueInvoice> {
	
}

