package com.jinyan.model;

import com.jinyan.model.base.BaseRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePermission extends BaseRolePermission<RolePermission> {
	
}

