package com.jinyan.model;

import com.jinyan.model.base.BaseSysFunction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysFunction extends BaseSysFunction<SysFunction> {
	
}

