package com.jinyan.model;

import com.jinyan.model.base.BaseSysRoleFunction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleFunction extends BaseSysRoleFunction<SysRoleFunction> {
	
}

