package com.jinyan.model;

import com.jinyan.model.base.BaseSysUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserRole extends BaseSysUserRole<SysUserRole> {
	
}

