package com.jinyan.model;

import com.jinyan.model.base.BaseUnusedHotel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UnusedHotel extends BaseUnusedHotel<UnusedHotel> {
	
}

