package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHotel<M extends BaseHotel<M>> extends Model<M> implements IBean {

	/**
	 * 高德酒店ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 高德酒店ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 此字段隐藏，不需要处理
	 */
	public void setTailnum(java.lang.Integer Tailnum) {
		set("Tailnum", Tailnum);
	}
	
	/**
	 * 此字段隐藏，不需要处理
	 */
	public java.lang.Integer getTailnum() {
		return getInt("Tailnum");
	}
	
	/**
	 * 艺龙酒店id
	 */
	public void setElongId(java.lang.Integer ElongId) {
		set("ElongId", ElongId);
	}
	
	/**
	 * 艺龙酒店id
	 */
	public java.lang.Integer getElongId() {
		return getInt("ElongId");
	}
	
	
	/**
	 * 艺龙酒店id
	 */
	public void setCtripHotelID(java.lang.Integer CtripHotelID) {
		set("CtripHotelID", CtripHotelID);
	}
	
	/**
	 * 艺龙酒店id
	 */
	public java.lang.Integer getCtripHotelID() {
		return getInt("CtripHotelID");
	}
	
	/**
	 * 酒店中文名称
	 */
	public void setHotelName(java.lang.String HotelName) {
		set("HotelName", HotelName);
	}
	
	/**
	 * 酒店中文名称
	 */
	public java.lang.String getHotelName() {
		return getStr("HotelName");
	}
	
	/**
	 * 酒店状态 0:有效 1:无效 2:删除
	 */
	public void setHotelStatus(java.lang.Integer HotelStatus) {
		set("HotelStatus", HotelStatus);
	}
	
	/**
	 * 酒店状态 0:有效 1:无效 2:删除
	 */
	public java.lang.Integer getHotelStatus() {
		return getInt("HotelStatus");
	}
	
	/**
	 * 挂牌星级
	 */
	public void setStarRate(java.lang.Integer StarRate) {
		set("StarRate", StarRate);
	}
	
	/**
	 * 挂牌星级
	 */
	public java.lang.Integer getStarRate() {
		return getInt("StarRate");
	}
	
	/**
	 * 艺龙推荐星级
	 */
	public void setCategory(java.lang.Integer Category) {
		set("Category", Category);
	}
	
	/**
	 * 艺龙推荐星级
	 */
	public java.lang.Integer getCategory() {
		return getInt("Category");
	}
	
	/**
	 * 电话
	 */
	public void setPhone(java.lang.String Phone) {
		set("Phone", Phone);
	}
	
	/**
	 * 电话
	 */
	public java.lang.String getPhone() {
		return getStr("Phone");
	}
	
	/**
	 * 品牌中文名称
	 */
	public void setBrandName(java.lang.String BrandName) {
		set("BrandName", BrandName);
	}
	
	/**
	 * 品牌中文名称
	 */
	public java.lang.String getBrandName() {
		return getStr("BrandName");
	}
	
	/**
	 * 高德纬度
	 */
	public void setGaodeLat(java.lang.String GaodeLat) {
		set("GaodeLat", GaodeLat);
	}
	
	/**
	 * 高德纬度
	 */
	public java.lang.String getGaodeLat() {
		return getStr("GaodeLat");
	}
	
	/**
	 * 高德经度
	 */
	public void setGaodeLon(java.lang.String GaodeLon) {
		set("GaodeLon", GaodeLon);
	}
	
	/**
	 * 高德经度
	 */
	public java.lang.String getGaodeLon() {
		return getStr("GaodeLon");
	}
	
	/**
	 * Baidu纬度
	 */
	public void setBaiduLat(java.lang.String BaiduLat) {
		set("BaiduLat", BaiduLat);
	}
	
	/**
	 * Baidu纬度
	 */
	public java.lang.String getBaiduLat() {
		return getStr("BaiduLat");
	}
	
	/**
	 * Baidu经度
	 */
	public void setBaiduLon(java.lang.String BaiduLon) {
		set("BaiduLon", BaiduLon);
	}
	
	/**
	 * Baidu经度
	 */
	public java.lang.String getBaiduLon() {
		return getStr("BaiduLon");
	}
	
	/**
	 * 主城市Id
	 */
	public void setCityId(java.lang.String CityId) {
		set("CityId", CityId);
	}
	
	/**
	 * 主城市Id
	 */
	public java.lang.String getCityId() {
		return getStr("CityId");
	}
	
	/**
	 * 城市中文名
	 */
	public void setCityName(java.lang.String CityName) {
		set("CityName", CityName);
	}
	
	/**
	 * 城市中文名
	 */
	public java.lang.String getCityName() {
		return getStr("CityName");
	}
	
	/**
	 * 客房总数量
	 */
	public void setRoomTotalAmount(java.lang.Integer RoomTotalAmount) {
		set("RoomTotalAmount", RoomTotalAmount);
	}
	
	/**
	 * 客房总数量
	 */
	public java.lang.Integer getRoomTotalAmount() {
		return getInt("RoomTotalAmount");
	}
	
	public void setAddress(java.lang.String Address) {
		set("Address", Address);
	}
	
	public java.lang.String getAddress() {
		return getStr("Address");
	}
	
	public void setHotelType(java.lang.Integer HotelType) {
		set("HotelType", HotelType);
	}
	
	public java.lang.Integer getHotelType() {
		return getInt("HotelType");
	}
	
	public void setElongIdStr(java.lang.String ElongIdStr) {
		set("ElongIdStr", ElongIdStr);
	}
	
	public java.lang.String getElongIdStr() {
		return getStr("ElongIdStr");
	}
	
	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}
	
	public void setUserpid(java.lang.Integer userpid) {
		set("userpid", userpid);
	}
	
	public java.lang.Integer getUserpid() {
		return getInt("userpid");
	}
	
	public void setDltel(java.lang.String dltel) {
		set("dltel", dltel);
	}
	
	public java.lang.String getDltel() {
		return getStr("dltel");
	}
	
	public void setDlname(java.lang.String dlname) {
		set("dlname", dlname);
	}
	
	public java.lang.String getDlname() {
		return getStr("dlname");
	}
	
	/**
	 * 1 下架
	 */
	public void setDown(java.lang.Integer down) {
		set("down", down);
	}
	
	/**
	 * 1 下架
	 */
	public java.lang.Integer getDown() {
		return getInt("down");
	}
	
	/**
	 * 1 是更新不到接口房态
	 */
	public void setNoroom(java.lang.Integer noroom) {
		set("noroom", noroom);
	}
	
	/**
	 * 1 是更新不到接口房态
	 */
	public java.lang.Integer getNoroom() {
		return getInt("noroom");
	}
	
	/**
	 * 佣金比例
	 */
	public void setCommissionRate(java.math.BigDecimal commissionRate) {
		set("commission_rate", commissionRate);
	}
	
	/**
	 * 佣金比例
	 */
	public java.math.BigDecimal getCommissionRate() {
		return get("commission_rate");
	}
	
	/**
	 * 联系人
	 */
	public void setContactName(java.lang.String contactName) {
		set("contact_name", contactName);
	}
	
	/**
	 * 联系人
	 */
	public java.lang.String getContactName() {
		return getStr("contact_name");
	}
	
	/**
	 * 联系电话
	 */
	public void setContactPhone(java.lang.String contactPhone) {
		set("contact_phone", contactPhone);
	}
	
	/**
	 * 联系电话
	 */
	public java.lang.String getContactPhone() {
		return getStr("contact_phone");
	}
	
	/**
	 * 1=酒店开票,2=CP提供发票
	 */
	public void setInvoiceMode(java.lang.Integer InvoiceMode) {
		set("InvoiceMode", InvoiceMode);
	}
	
	/**
	 * 1=酒店开票,2=CP提供发票
	 */
	public java.lang.Integer getInvoiceMode() {
		return getInt("InvoiceMode");
	}
	
	/**
	 * 0是艺龙产品，1是非艺龙
	 */
	public void setSource(java.lang.Integer source) {
		set("source", source);
	}
	
	/**
	 * 0是艺龙产品，1是非艺龙
	 */
	public java.lang.Integer getSource() {
		return getInt("source");
	}
	
	
	/**
	 * 创建时间
	 */
	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreated() {
		return getDate("created");
	}
	
}

