package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFormSql<M extends BaseFormSql<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 树id
	 */
	public void setTreeId(java.lang.String treeId) {
		set("tree_id", treeId);
	}
	
	/**
	 * 树id
	 */
	public java.lang.String getTreeId() {
		return getStr("tree_id");
	}
	
	/**
	 * sql编号
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * sql编号
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}
	
	/**
	 * sql名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * sql名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * sql内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * sql内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * sql说明
	 */
	public void setDescp(java.lang.String descp) {
		set("descp", descp);
	}
	
	/**
	 * sql说明
	 */
	public java.lang.String getDescp() {
		return getStr("descp");
	}
	
	/**
	 * 数据源配置名称
	 */
	public void setConfigName(java.lang.String configName) {
		set("config_name", configName);
	}
	
	/**
	 * 数据源配置名称
	 */
	public java.lang.String getConfigName() {
		return getStr("config_name");
	}
	
}

