package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUnusedRoom<M extends BaseUnusedRoom<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 0正常 1删除
	 */
	public void setIsDel(java.lang.Boolean isDel) {
		set("is_del", isDel);
	}
	
	/**
	 * 0正常 1删除
	 */
	public java.lang.Boolean getIsDel() {
		return get("is_del");
	}
	
	/**
	 * 软删除
	 */
	public void setDeleteTime(java.lang.Integer deleteTime) {
		set("delete_time", deleteTime);
	}
	
	/**
	 * 软删除
	 */
	public java.lang.Integer getDeleteTime() {
		return getInt("delete_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.lang.Integer updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.lang.Integer getUpdateTime() {
		return getInt("update_time");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.lang.Integer createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.Integer getCreateTime() {
		return getInt("create_time");
	}
	
	public void setRoomid(java.lang.Integer roomid) {
		set("roomid", roomid);
	}
	
	public java.lang.Integer getRoomid() {
		return getInt("roomid");
	}
	
	public void setRoomname(java.lang.String roomname) {
		set("roomname", roomname);
	}
	
	public java.lang.String getRoomname() {
		return getStr("roomname");
	}
	
	public void setEid(java.lang.String eid) {
		set("eid", eid);
	}
	
	public java.lang.String getEid() {
		return getStr("eid");
	}
	
	public void setRoomsall(java.lang.Integer roomsall) {
		set("roomsall", roomsall);
	}
	
	public java.lang.Integer getRoomsall() {
		return getInt("roomsall");
	}
	
	public void setRoomsleft(java.lang.Integer roomsleft) {
		set("roomsleft", roomsleft);
	}
	
	public java.lang.Integer getRoomsleft() {
		return getInt("roomsleft");
	}
	
	public void setUnusedhotelid(java.lang.Integer unusedhotelid) {
		set("unusedhotelid", unusedhotelid);
	}
	
	public java.lang.Integer getUnusedhotelid() {
		return getInt("unusedhotelid");
	}
	
	/**
	 * 底价
	 */
	public void setCost(java.lang.Double cost) {
		set("cost", cost);
	}
	
	/**
	 * 底价
	 */
	public java.lang.Double getCost() {
		return getDouble("cost");
	}
	
}

