package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUnusedHotel<M extends BaseUnusedHotel<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 0正常 1删除
	 */
	public void setIsDel(java.lang.Boolean isDel) {
		set("is_del", isDel);
	}
	
	/**
	 * 0正常 1删除
	 */
	public java.lang.Boolean getIsDel() {
		return get("is_del");
	}
	
	/**
	 * 软删除
	 */
	public void setDeleteTime(java.lang.Integer deleteTime) {
		set("delete_time", deleteTime);
	}
	
	/**
	 * 软删除
	 */
	public java.lang.Integer getDeleteTime() {
		return getInt("delete_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.lang.Integer updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.lang.Integer getUpdateTime() {
		return getInt("update_time");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.lang.Integer createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.Integer getCreateTime() {
		return getInt("create_time");
	}
	
	/**
	 * 剩总量
	 */
	public void setExcludequantity(java.lang.Integer excludequantity) {
		set("excludequantity", excludequantity);
	}
	
	/**
	 * 剩总量
	 */
	public java.lang.Integer getExcludequantity() {
		return getInt("excludequantity");
	}
	
	/**
	 * 可免费数
	 */
	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}
	
	/**
	 * 可免费数
	 */
	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}
	
	public void setBak(java.lang.String bak) {
		set("bak", bak);
	}
	
	public java.lang.String getBak() {
		return getStr("bak");
	}
	
	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}
	
	public void setUserpid(java.lang.Integer userpid) {
		set("userpid", userpid);
	}
	
	public java.lang.Integer getUserpid() {
		return getInt("userpid");
	}
	
	/**
	 * 回款金额
	 */
	public void setRefundprice(java.lang.Double refundprice) {
		set("refundprice", refundprice);
	}
	
	/**
	 * 回款金额
	 */
	public java.lang.Double getRefundprice() {
		return getDouble("refundprice");
	}
	
	/**
	 * 回款日期
	 */
	public void setRefunddate(java.lang.String refunddate) {
		set("refunddate", refunddate);
	}
	
	/**
	 * 回款日期
	 */
	public java.lang.String getRefunddate() {
		return getStr("refunddate");
	}
	
	/**
	 * 实际售卖完日期
	 */
	public void setSolddate(java.lang.String solddate) {
		set("solddate", solddate);
	}
	
	/**
	 * 实际售卖完日期
	 */
	public java.lang.String getSolddate() {
		return getStr("solddate");
	}
	
	/**
	 * 到期提醒
	 */
	public void setNoticedate(java.lang.String noticedate) {
		set("noticedate", noticedate);
	}
	
	/**
	 * 到期提醒
	 */
	public java.lang.String getNoticedate() {
		return getStr("noticedate");
	}
	
	/**
	 * 0,未充值，1已充值
	 */
	public void setRecharged(java.lang.Integer recharged) {
		set("recharged", recharged);
	}
	
	/**
	 * 0,未充值，1已充值
	 */
	public java.lang.Integer getRecharged() {
		return getInt("recharged");
	}
	
	/**
	 * 充值金额
	 */
	public void setPrice(java.lang.Double price) {
		set("price", price);
	}
	
	/**
	 * 充值金额
	 */
	public java.lang.Double getPrice() {
		return getDouble("price");
	}
	
	/**
	 * 销售
	 */
	public void setSaler(java.lang.Integer saler) {
		set("saler", saler);
	}
	
	/**
	 * 销售
	 */
	public java.lang.Integer getSaler() {
		return getInt("saler");
	}
	
	public void setPdfs(java.lang.String pdfs) {
		set("pdfs", pdfs);
	}
	
	public java.lang.String getPdfs() {
		return getStr("pdfs");
	}
	
	public void setPics(java.lang.String pics) {
		set("pics", pics);
	}
	
	public java.lang.String getPics() {
		return getStr("pics");
	}
	
	public void setLock(java.lang.Integer lock) {
		set("lock", lock);
	}
	
	public java.lang.Integer getLock() {
		return getInt("lock");
	}
	
	public void setLockdate(java.lang.String lockdate) {
		set("lockdate", lockdate);
	}
	
	public java.lang.String getLockdate() {
		return getStr("lockdate");
	}
	
	public void setEid(java.lang.String eid) {
		set("eid", eid);
	}
	
	public java.lang.String getEid() {
		return getStr("eid");
	}
	
	public void setHotelname(java.lang.String hotelname) {
		set("hotelname", hotelname);
	}
	
	public java.lang.String getHotelname() {
		return getStr("hotelname");
	}
	
	public void setHide(java.lang.Integer hide) {
		set("hide", hide);
	}
	
	public java.lang.Integer getHide() {
		return getInt("hide");
	}
	
	public void setCuruserid(java.lang.Integer curuserid) {
		set("curuserid", curuserid);
	}
	
	public java.lang.Integer getCuruserid() {
		return getInt("curuserid");
	}
	
	public void setQudao(java.lang.Integer qudao) {
		set("qudao", qudao);
	}
	
	public java.lang.Integer getQudao() {
		return getInt("qudao");
	}
	
}

