package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePic<M extends BasePic<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setRoomid(java.lang.Integer roomid) {
		set("roomid", roomid);
	}
	
	public java.lang.Integer getRoomid() {
		return getInt("roomid");
	}
	
	public void setImageurl(java.lang.String imageurl) {
		set("imageurl", imageurl);
	}
	
	public java.lang.String getImageurl() {
		return getStr("imageurl");
	}
	
	public void setImagetype(java.lang.String imagetype) {
		set("imagetype", imagetype);
	}
	
	public java.lang.String getImagetype() {
		return getStr("imagetype");
	}
	
	public void setImagename(java.lang.String imagename) {
		set("imagename", imagename);
	}
	
	public java.lang.String getImagename() {
		return getStr("imagename");
	}
	
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}
	
}

