package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysOrg<M extends BaseSysOrg<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 部门编号和主键默认
	 */
	public void setOrgCode(java.lang.String orgCode) {
		set("org_code", orgCode);
	}
	
	/**
	 * 部门编号和主键默认
	 */
	public java.lang.String getOrgCode() {
		return getStr("org_code");
	}
	
	/**
	 * 上级部门编号
	 */
	public void setParentid(java.lang.String parentid) {
		set("parentid", parentid);
	}
	
	/**
	 * 上级部门编号
	 */
	public java.lang.String getParentid() {
		return getStr("parentid");
	}
	
	/**
	 * 上级部门名称
	 */
	public void setParentidName(java.lang.String parentidName) {
		set("parentid_name", parentidName);
	}
	
	/**
	 * 上级部门名称
	 */
	public java.lang.String getParentidName() {
		return getStr("parentid_name");
	}
	
	/**
	 * 部门名称
	 */
	public void setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
	}
	
	/**
	 * 部门名称
	 */
	public java.lang.String getOrgName() {
		return getStr("org_name");
	}
	
	/**
	 * 部门负责人姓名
	 */
	public void setChief(java.lang.String chief) {
		set("chief", chief);
	}
	
	/**
	 * 部门负责人姓名
	 */
	public java.lang.String getChief() {
		return getStr("chief");
	}
	
	/**
	 * 部门负责人电话
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 部门负责人电话
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	/**
	 * 部门负责人手机号
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 部门负责人手机号
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	/**
	 * 部门负责人邮件
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 部门负责人邮件
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	/**
	 * 描述
	 */
	public void setDescript(java.lang.String descript) {
		set("descript", descript);
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getDescript() {
		return getStr("descript");
	}
	
	/**
	 * 级别
	 */
	public void setLev(java.lang.Integer lev) {
		set("lev", lev);
	}
	
	/**
	 * 级别
	 */
	public java.lang.Integer getLev() {
		return getInt("lev");
	}
	
	/**
	 * 是否停用
1：停用；
0：启用；
	 */
	public void setIsstop(java.lang.Integer isstop) {
		set("isstop", isstop);
	}
	
	/**
	 * 是否停用
1：停用；
0：启用；
	 */
	public java.lang.Integer getIsstop() {
		return getInt("isstop");
	}
	
}

