package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFormView<M extends BaseFormView<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setTreeId(java.lang.String treeId) {
		set("tree_id", treeId);
	}
	
	public java.lang.String getTreeId() {
		return getStr("tree_id");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setTemplateView(java.lang.String templateView) {
		set("template_view", templateView);
	}
	
	public java.lang.String getTemplateView() {
		return getStr("template_view");
	}
	
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public void setDescp(java.lang.String descp) {
		set("descp", descp);
	}
	
	public java.lang.String getDescp() {
		return getStr("descp");
	}
	
}

