package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFileUploaded<M extends BaseFileUploaded<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public void setFileName(java.lang.String fileName) {
		set("file_name", fileName);
	}
	
	public java.lang.String getFileName() {
		return getStr("file_name");
	}
	
	/**
	 * KB
	 */
	public void setFileSize(java.lang.Long fileSize) {
		set("file_size", fileSize);
	}
	
	/**
	 * KB
	 */
	public java.lang.Long getFileSize() {
		return getLong("file_size");
	}
	
	public void setSavePath(java.lang.String savePath) {
		set("save_path", savePath);
	}
	
	public java.lang.String getSavePath() {
		return getStr("save_path");
	}
	
	public void setObjectId(java.lang.String objectId) {
		set("object_id", objectId);
	}
	
	public java.lang.String getObjectId() {
		return getStr("object_id");
	}
	
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}
	
}

