package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHotelview<M extends BaseHotelview<M>> extends Model<M> implements IBean {

	/**
	 * 高德酒店ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 高德酒店ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public void setGdid(java.lang.Long gdid) {
		set("gdid", gdid);
	}
	
	public java.lang.Long getGdid() {
		return getLong("gdid");
	}
	
	/**
	 * 艺龙酒店id
	 */
	public void setElongId(java.lang.Integer ElongId) {
		set("ElongId", ElongId);
	}
	
	/**
	 * 艺龙酒店id
	 */
	public java.lang.Integer getElongId() {
		return getInt("ElongId");
	}
	
	/**
	 * 酒店中文名称
	 */
	public void setHotelName(java.lang.String HotelName) {
		set("HotelName", HotelName);
	}
	
	/**
	 * 酒店中文名称
	 */
	public java.lang.String getHotelName() {
		return getStr("HotelName");
	}
	
	public void setStartDate(java.lang.String StartDate) {
		set("StartDate", StartDate);
	}
	
	public java.lang.String getStartDate() {
		return getStr("StartDate");
	}
	
	public void setEndDate(java.lang.String EndDate) {
		set("EndDate", EndDate);
	}
	
	public java.lang.String getEndDate() {
		return getStr("EndDate");
	}
	
	public void setHaveroom(java.lang.Integer haveroom) {
		set("haveroom", haveroom);
	}
	
	public java.lang.Integer getHaveroom() {
		return getInt("haveroom");
	}
	
	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return getDate("created");
	}
	
	public void setCache(java.lang.Integer cache) {
		set("cache", cache);
	}
	
	public java.lang.Integer getCache() {
		return getInt("cache");
	}
	
	public void setIssubmit(java.lang.Integer issubmit) {
		set("issubmit", issubmit);
	}
	
	public java.lang.Integer getIssubmit() {
		return getInt("issubmit");
	}
	
	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}
	
	public void setUserpid(java.lang.Integer userpid) {
		set("userpid", userpid);
	}
	
	public java.lang.Integer getUserpid() {
		return getInt("userpid");
	}
	
}

