package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReissueInvoice<M extends BaseReissueInvoice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setAmapOrderID(java.lang.String amapOrderID) {
		set("amapOrderID", amapOrderID);
	}
	
	public java.lang.String getAmapOrderID() {
		return getStr("amapOrderID");
	}
	
	public void setCpOrderID(java.lang.String cpOrderID) {
		set("cpOrderID", cpOrderID);
	}
	
	public java.lang.String getCpOrderID() {
		return getStr("cpOrderID");
	}
	
	public void setInvoiceType(java.lang.Integer invoiceType) {
		set("invoiceType", invoiceType);
	}
	
	public java.lang.Integer getInvoiceType() {
		return getInt("invoiceType");
	}
	
	public void setInvoiceTitleType(java.lang.Integer invoiceTitleType) {
		set("invoiceTitleType", invoiceTitleType);
	}
	
	public java.lang.Integer getInvoiceTitleType() {
		return getInt("invoiceTitleType");
	}
	
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	public void setTaxpayerNumber(java.lang.String taxpayerNumber) {
		set("taxpayerNumber", taxpayerNumber);
	}
	
	public java.lang.String getTaxpayerNumber() {
		return getStr("taxpayerNumber");
	}
	
	public void setInvoiceAmount(java.lang.Double invoiceAmount) {
		set("invoiceAmount", invoiceAmount);
	}
	
	public java.lang.Double getInvoiceAmount() {
		return getDouble("invoiceAmount");
	}
	
	public void setBody(java.lang.String body) {
		set("body", body);
	}
	
	public java.lang.String getBody() {
		return getStr("body");
	}
	
	public void setInvoiceRemark(java.lang.String invoiceRemark) {
		set("invoiceRemark", invoiceRemark);
	}
	
	public java.lang.String getInvoiceRemark() {
		return getStr("invoiceRemark");
	}
	
	public void setPostPayType(java.lang.String postPayType) {
		set("postPayType", postPayType);
	}
	
	public java.lang.String getPostPayType() {
		return getStr("postPayType");
	}
	
	public void setPresonName(java.lang.String presonName) {
		set("presonName", presonName);
	}
	
	public java.lang.String getPresonName() {
		return getStr("presonName");
	}
	
	public void setPhoneNumber(java.lang.String phoneNumber) {
		set("phoneNumber", phoneNumber);
	}
	
	public java.lang.String getPhoneNumber() {
		return getStr("phoneNumber");
	}
	
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}
	
	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}
	
	public void setDistrict(java.lang.String district) {
		set("district", district);
	}
	
	public java.lang.String getDistrict() {
		return getStr("district");
	}
	
	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}
	
	public java.lang.String getDetail() {
		return getStr("detail");
	}
	
	public void setConpanyName(java.lang.String conpanyName) {
		set("conpanyName", conpanyName);
	}
	
	public java.lang.String getConpanyName() {
		return getStr("conpanyName");
	}
	
	public void setCompanyAddress(java.lang.String companyAddress) {
		set("companyAddress", companyAddress);
	}
	
	public java.lang.String getCompanyAddress() {
		return getStr("companyAddress");
	}
	
	public void setCompanyPhone(java.lang.String companyPhone) {
		set("companyPhone", companyPhone);
	}
	
	public java.lang.String getCompanyPhone() {
		return getStr("companyPhone");
	}
	
	public void setCompanyBankName(java.lang.String companyBankName) {
		set("companyBankName", companyBankName);
	}
	
	public java.lang.String getCompanyBankName() {
		return getStr("companyBankName");
	}
	
	public void setCompanyBankAccount(java.lang.String companyBankAccount) {
		set("companyBankAccount", companyBankAccount);
	}
	
	public java.lang.String getCompanyBankAccount() {
		return getStr("companyBankAccount");
	}
	
}

