package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreated() {
		return getDate("created");
	}
	
	/**
	 * 最后更新时间
	 */
	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}
	
	/**
	 * 最后更新时间
	 */
	public java.util.Date getUpdated() {
		return getDate("updated");
	}
	
	/**
	 * 高德订单号
	 */
	public void setAmapOrderID(java.lang.String AmapOrderID) {
		set("AmapOrderID", AmapOrderID);
	}
	
	/**
	 * 高德订单号
	 */
	public java.lang.String getAmapOrderID() {
		return getStr("AmapOrderID");
	}
	
	/**
	 * 高德酒店id
	 */
	public void setHotelID(java.lang.Long HotelID) {
		set("HotelID", HotelID);
	}
	
	/**
	 * 高德酒店id
	 */
	public java.lang.Long getHotelID() {
		return getLong("HotelID");
	}
	
	/**
	 * 房型编号
	 */
	public void setRoomID(java.lang.String RoomID) {
		set("RoomID", RoomID);
	}
	
	/**
	 * 房型编号
	 */
	public java.lang.String getRoomID() {
		return getStr("RoomID");
	}
	
	/**
	 * 预订间数
	 */
	public void setQuantity(java.lang.Integer Quantity) {
		set("Quantity", Quantity);
	}
	
	/**
	 * 预订间数
	 */
	public java.lang.Integer getQuantity() {
		return getInt("Quantity");
	}
	
	/**
	 * 报价编号
	 */
	public void setRatePlanID(java.lang.String RatePlanID) {
		set("RatePlanID", RatePlanID);
	}
	
	/**
	 * 报价编号
	 */
	public java.lang.String getRatePlanID() {
		return getStr("RatePlanID");
	}
	
	/**
	 * 入住日期
	 */
	public void setArrival(java.lang.String Arrival) {
		set("Arrival", Arrival);
	}
	
	/**
	 * 入住日期
	 */
	public java.lang.String getArrival() {
		return getStr("Arrival");
	}
	
	/**
	 * 离店日期
	 */
	public void setDeparture(java.lang.String Departure) {
		set("Departure", Departure);
	}
	
	/**
	 * 离店日期
	 */
	public java.lang.String getDeparture() {
		return getStr("Departure");
	}
	
	/**
	 * 最早到店时间
	 */
	public void setEarlyArrivalTime(java.lang.String EarlyArrivalTime) {
		set("EarlyArrivalTime", EarlyArrivalTime);
	}
	
	/**
	 * 最早到店时间
	 */
	public java.lang.String getEarlyArrivalTime() {
		return getStr("EarlyArrivalTime");
	}
	
	/**
	 * 最晚到店时间
	 */
	public void setLastArrivalTime(java.lang.String LastArrivalTime) {
		set("LastArrivalTime", LastArrivalTime);
	}
	
	/**
	 * 最晚到店时间
	 */
	public java.lang.String getLastArrivalTime() {
		return getStr("LastArrivalTime");
	}
	
	/**
	 * 实际入住人数
	 */
	public void setPerson(java.lang.Integer Person) {
		set("Person", Person);
	}
	
	/**
	 * 实际入住人数
	 */
	public java.lang.Integer getPerson() {
		return getInt("Person");
	}
	
	/**
	 * 联系人姓名
	 */
	public void setPersonName(java.lang.String PersonName) {
		set("PersonName", PersonName);
	}
	
	/**
	 * 联系人姓名
	 */
	public java.lang.String getPersonName() {
		return getStr("PersonName");
	}
	
	/**
	 * 联系人手机号
	 */
	public void setPersonMobile(java.lang.String PersonMobile) {
		set("PersonMobile", PersonMobile);
	}
	
	/**
	 * 联系人手机号
	 */
	public java.lang.String getPersonMobile() {
		return getStr("PersonMobile");
	}
	
	/**
	 * 联系人邮箱
	 */
	public void setPersonEmail(java.lang.String PersonEmail) {
		set("PersonEmail", PersonEmail);
	}
	
	/**
	 * 联系人邮箱
	 */
	public java.lang.String getPersonEmail() {
		return getStr("PersonEmail");
	}
	
	/**
	 * 底价
	 */
	public void setTotalCost(java.math.BigDecimal TotalCost) {
		set("TotalCost", TotalCost);
	}
	
	/**
	 * 底价
	 */
	public java.math.BigDecimal getTotalCost() {
		return get("TotalCost");
	}
	
	/**
	 * 订单卖价总金额，即当前订单价格
	 */
	public void setTotalPrice(java.math.BigDecimal TotalPrice) {
		set("TotalPrice", TotalPrice);
	}
	
	/**
	 * 订单卖价总金额，即当前订单价格
	 */
	public java.math.BigDecimal getTotalPrice() {
		return get("TotalPrice");
	}
	
	/**
	 * 订单实付金额
	 */
	public void setOrderRealPrice(java.math.BigDecimal OrderRealPrice) {
		set("OrderRealPrice", OrderRealPrice);
	}
	
	/**
	 * 订单实付金额
	 */
	public java.math.BigDecimal getOrderRealPrice() {
		return get("OrderRealPrice");
	}
	
	/**
	 * 价格类型(PP:预付 FG:现付 PKG:包价)
	 */
	public void setBalanceType(java.lang.String BalanceType) {
		set("BalanceType", BalanceType);
	}
	
	/**
	 * 价格类型(PP:预付 FG:现付 PKG:包价)
	 */
	public java.lang.String getBalanceType() {
		return getStr("BalanceType");
	}
	
	/**
	 * 入驻客户信息(多个,用逗号隔开)
	 */
	public void setGuests(java.lang.String Guests) {
		set("Guests", Guests);
	}
	
	/**
	 * 入驻客户信息(多个,用逗号隔开)
	 */
	public java.lang.String getGuests() {
		return getStr("Guests");
	}
	
	/**
	 * 备注信息
	 */
	public void setNotice(java.lang.String Notice) {
		set("Notice", Notice);
	}
	
	/**
	 * 备注信息
	 */
	public java.lang.String getNotice() {
		return getStr("Notice");
	}
	
	/**
	 * 订单状态(兼容艺龙状态描述)
	 */
	public void setEstatus(java.lang.String estatus) {
		set("estatus", estatus);
	}
	
	/**
	 * 订单状态(兼容艺龙状态描述)
	 */
	public java.lang.String getEstatus() {
		return getStr("estatus");
	}
	
	/**
	 * 1 申请取消 2 已处理
	 */
	public void setCancelstatus(java.lang.Integer cancelstatus) {
		set("cancelstatus", cancelstatus);
	}
	
	/**
	 * 1 申请取消 2 已处理
	 */
	public java.lang.Integer getCancelstatus() {
		return getInt("cancelstatus");
	}
	
	/**
	 * 价格日历
	 */
	public void setDayprice(java.lang.String dayprice) {
		set("dayprice", dayprice);
	}
	
	/**
	 * 价格日历
	 */
	public java.lang.String getDayprice() {
		return getStr("dayprice");
	}
	
	/**
	 * 取消说明
	 */
	public void setCancelshow(java.lang.String cancelshow) {
		set("cancelshow", cancelshow);
	}
	
	/**
	 * 取消说明
	 */
	public java.lang.String getCancelshow() {
		return getStr("cancelshow");
	}
	
	public void setCancelReqDatetime(java.util.Date cancelReqDatetime) {
		set("cancelReqDatetime", cancelReqDatetime);
	}
	
	public java.util.Date getCancelReqDatetime() {
		return getDate("cancelReqDatetime");
	}
	
	public void setCanceledDatetime(java.util.Date canceledDatetime) {
		set("canceledDatetime", canceledDatetime);
	}
	
	public java.util.Date getCanceledDatetime() {
		return getDate("canceledDatetime");
	}
	
	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}
	
	public void setUserpid(java.lang.Integer userpid) {
		set("userpid", userpid);
	}
	
	public java.lang.Integer getUserpid() {
		return getInt("userpid");
	}
	
	public void setBak(java.lang.String bak) {
		set("bak", bak);
	}
	
	public java.lang.String getBak() {
		return getStr("bak");
	}
	
	public void setDiffstatus(java.lang.Integer diffstatus) {
		set("diffstatus", diffstatus);
	}
	
	public java.lang.Integer getDiffstatus() {
		return getInt("diffstatus");
	}
	
	public void setPenaltyAmount(java.math.BigDecimal PenaltyAmount) {
		set("PenaltyAmount", PenaltyAmount);
	}
	
	public java.math.BigDecimal getPenaltyAmount() {
		return get("PenaltyAmount");
	}
	
	public void setConfirmDatetime(java.util.Date confirmDatetime) {
		set("confirmDatetime", confirmDatetime);
	}
	
	public java.util.Date getConfirmDatetime() {
		return getDate("confirmDatetime");
	}
	
	/**
	 * 免房订单
	 */
	public void setIsFree(java.lang.Integer isFree) {
		set("is_free", isFree);
	}
	
	/**
	 * 免房订单
	 */
	public java.lang.Integer getIsFree() {
		return getInt("is_free");
	}
	
	/**
	 * 订单部分退款金额 注：用户实际预订3天，需取消最后一天时，该字段传退款金额，仅部分退场景传
	 */
	public void setPortionRefundAmount(java.math.BigDecimal PortionRefundAmount) {
		set("PortionRefundAmount", PortionRefundAmount);
	}
	
	/**
	 * 订单部分退款金额 注：用户实际预订3天，需取消最后一天时，该字段传退款金额，仅部分退场景传
	 */
	public java.math.BigDecimal getPortionRefundAmount() {
		return get("PortionRefundAmount");
	}
	
	/**
	 * 客户实际支付
	 */
	public void setPriceOrder(java.math.BigDecimal priceOrder) {
		set("priceOrder", priceOrder);
	}
	
	/**
	 * 客户实际支付
	 */
	public java.math.BigDecimal getPriceOrder() {
		return get("priceOrder");
	}
	
	/**
	 * 高德读取到的状态
	 */
	public void setGdestatus(java.lang.String gdestatus) {
		set("gdestatus", gdestatus);
	}
	
	/**
	 * 高德读取到的状态
	 */
	public java.lang.String getGdestatus() {
		return getStr("gdestatus");
	}
	
	/**
	 * 高德读到状态时间
	 */
	public void setGdestatusTime(java.util.Date gdestatusTime) {
		set("gdestatus_time", gdestatusTime);
	}
	
	/**
	 * 高德读到状态时间
	 */
	public java.util.Date getGdestatusTime() {
		return getDate("gdestatus_time");
	}
	
}

