package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUserRole<M extends BaseSysUserRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setRoleCode(java.lang.String roleCode) {
		set("role_code", roleCode);
	}
	
	public java.lang.String getRoleCode() {
		return getStr("role_code");
	}
	
	public void setUserCode(java.lang.String userCode) {
		set("user_code", userCode);
	}
	
	public java.lang.String getUserCode() {
		return getStr("user_code");
	}
	
}

