package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHotelquyuGdRooms<M extends BaseHotelquyuGdRooms<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}
	
	public void setHide(java.lang.Integer hide) {
		set("hide", hide);
	}
	
	public java.lang.Integer getHide() {
		return getInt("hide");
	}
	
	public void setUserpid(java.lang.Integer userpid) {
		set("userpid", userpid);
	}
	
	public java.lang.Integer getUserpid() {
		return getInt("userpid");
	}
	
	public void setCreatetime(java.lang.Integer createtime) {
		set("createtime", createtime);
	}
	
	public java.lang.Integer getCreatetime() {
		return getInt("createtime");
	}
	
	public void setEid(java.lang.String eid) {
		set("eid", eid);
	}
	
	public java.lang.String getEid() {
		return getStr("eid");
	}
	
	public void setBak(java.lang.String bak) {
		set("bak", bak);
	}
	
	public java.lang.String getBak() {
		return getStr("bak");
	}
	
	public void setUpdatetime(java.lang.Integer updatetime) {
		set("updatetime", updatetime);
	}
	
	public java.lang.Integer getUpdatetime() {
		return getInt("updatetime");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setZid(java.lang.Integer zid) {
		set("zid", zid);
	}
	
	public java.lang.Integer getZid() {
		return getInt("zid");
	}
	
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}
	
	/**
	 * roomname
	 */
	public void setRoomid(java.lang.String roomid) {
		set("roomid", roomid);
	}
	
	/**
	 * roomname
	 */
	public java.lang.String getRoomid() {
		return getStr("roomid");
	}
	
	public void setRoomname(java.lang.String roomname) {
		set("roomname", roomname);
	}
	
	public java.lang.String getRoomname() {
		return getStr("roomname");
	}
	
	/**
	 * 房型面积
	 */
	public void setArea(java.lang.String area) {
		set("area", area);
	}
	
	/**
	 * 房型面积
	 */
	public java.lang.String getArea() {
		return getStr("area");
	}
	
	public void setFloor(java.lang.String floor) {
		set("floor", floor);
	}
	
	public java.lang.String getFloor() {
		return getStr("floor");
	}
	
	public void setBedtype(java.lang.String bedtype) {
		set("bedtype", bedtype);
	}
	
	public java.lang.String getBedtype() {
		return getStr("bedtype");
	}
	
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	public void setCapacity(java.lang.Integer capacity) {
		set("capacity", capacity);
	}
	
	public java.lang.Integer getCapacity() {
		return getInt("capacity");
	}
	
	public void setAmount(java.lang.Integer amount) {
		set("amount", amount);
	}
	
	public java.lang.Integer getAmount() {
		return getInt("amount");
	}
	
	public void setBroadnetAccess(java.lang.Integer broadnetAccess) {
		set("broadnetAccess", broadnetAccess);
	}
	
	public java.lang.Integer getBroadnetAccess() {
		return getInt("broadnetAccess");
	}
	
	public void setWeekendprice(java.math.BigDecimal weekendprice) {
		set("weekendprice", weekendprice);
	}
	
	public java.math.BigDecimal getWeekendprice() {
		return get("weekendprice");
	}
	
}

