package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLoginLog<M extends BaseLoginLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 登录使用的账户名
	 */
	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}
	
	/**
	 * 登录使用的账户名
	 */
	public java.lang.String getUserName() {
		return getStr("userName");
	}
	
	/**
	 * 登录成功的accountId
	 */
	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	/**
	 * 登录成功的accountId
	 */
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}
	
	/**
	 * 登录成功为1,否则为0
	 */
	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	/**
	 * 登录成功为1,否则为0
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}
	
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}
	
	public void setPort(java.lang.Integer port) {
		set("port", port);
	}
	
	public java.lang.Integer getPort() {
		return getInt("port");
	}
	
	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return getDate("created");
	}
	
}

