package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataSource<M extends BaseDataSource<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * dbType
	 */
	public void setDbType(java.lang.String dbType) {
		set("db_type", dbType);
	}
	
	/**
	 * dbType
	 */
	public java.lang.String getDbType() {
		return getStr("db_type");
	}
	
	/**
	 * jdbcUrl
	 */
	public void setJdbcUrl(java.lang.String jdbcUrl) {
		set("jdbc_url", jdbcUrl);
	}
	
	/**
	 * jdbcUrl
	 */
	public java.lang.String getJdbcUrl() {
		return getStr("jdbc_url");
	}
	
	/**
	 * user
	 */
	public void setUser(java.lang.String user) {
		set("user", user);
	}
	
	/**
	 * user
	 */
	public java.lang.String getUser() {
		return getStr("user");
	}
	
	/**
	 * password
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * password
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * configName
	 */
	public void setConfigName(java.lang.String configName) {
		set("config_name", configName);
	}
	
	/**
	 * configName
	 */
	public java.lang.String getConfigName() {
		return getStr("config_name");
	}
	
	/**
	 * 标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	/**
	 * 开机启动（0：否，1：是）
	 */
	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	/**
	 * 开机启动（0：否，1：是）
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}
	
	/**
	 * 启动（0：否，1：是）
	 */
	public void setStart(java.lang.Integer start) {
		set("start", start);
	}
	
	/**
	 * 启动（0：否，1：是）
	 */
	public java.lang.Integer getStart() {
		return getInt("start");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
}

