package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStore<M extends BaseStore<M>> extends Model<M> implements IBean {

	/**
	 * id
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * id
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 门店id
	 */
	public void setStoreOuterId(java.lang.String storeOuterId) {
		set("storeOuterId", storeOuterId);
	}
	
	/**
	 * 门店id
	 */
	public java.lang.String getStoreOuterId() {
		return getStr("storeOuterId");
	}
	
	/**
	 * 艺龙酒店id
	 */
	public void setElongid(java.lang.String elongid) {
		set("elongid", elongid);
	}
	
	/**
	 * 艺龙酒店id
	 */
	public java.lang.String getElongid() {
		return getStr("elongid");
	}
	
	/**
	 * 酒店中文名称
	 */
	public void setHotelName(java.lang.String HotelName) {
		set("HotelName", HotelName);
	}
	
	/**
	 * 酒店中文名称
	 */
	public java.lang.String getHotelName() {
		return getStr("HotelName");
	}
	
	/**
	 * poiid
	 */
	public void setPoiid(java.lang.String poiid) {
		set("poiid", poiid);
	}
	
	/**
	 * poiid
	 */
	public java.lang.String getPoiid() {
		return getStr("poiid");
	}
	
	public void setUpdatetime(java.lang.Integer updatetime) {
		set("updatetime", updatetime);
	}
	
	public java.lang.Integer getUpdatetime() {
		return getInt("updatetime");
	}
	
}

