package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderChange<M extends BaseOrderChange<M>> extends Model<M> implements IBean {

	/**
	 * 更新时间
	 */
	public void setUpdate(java.util.Date update) {
		set("update", update);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdate() {
		return getDate("update");
	}
	
	/**
	 * 高德订单号
	 */
	public void setAmapOrderID(java.lang.String AmapOrderID) {
		set("AmapOrderID", AmapOrderID);
	}
	
	/**
	 * 高德订单号
	 */
	public java.lang.String getAmapOrderID() {
		return getStr("AmapOrderID");
	}
	
	/**
	 * 供应商订单号，就是gd_order中的id
	 */
	public void setCpOrderID(java.lang.Integer CpOrderID) {
		set("CpOrderID", CpOrderID);
	}
	
	/**
	 * 供应商订单号，就是gd_order中的id
	 */
	public java.lang.Integer getCpOrderID() {
		return getInt("CpOrderID");
	}
	
}

