package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHotelroomChg<M extends BaseHotelroomChg<M>> extends Model<M> implements IBean {

	/**
	 * 高德酒店ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 高德酒店ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
}

