package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEbookingPrice<M extends BaseEbookingPrice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 酒店id
	 */
	public void setHotelId(java.lang.String hotelId) {
		set("hotel_id", hotelId);
	}
	
	/**
	 * 酒店id
	 */
	public java.lang.String getHotelId() {
		return getStr("hotel_id");
	}
	
	/**
	 * 计划id
	 */
	public void setPricePlanId(java.lang.Integer pricePlanId) {
		set("price_plan_id", pricePlanId);
	}
	
	/**
	 * 计划id
	 */
	public java.lang.Integer getPricePlanId() {
		return getInt("price_plan_id");
	}
	
	/**
	 * 房型id
	 */
	public void setRoomTypeId(java.lang.Integer roomTypeId) {
		set("room_type_id", roomTypeId);
	}
	
	/**
	 * 房型id
	 */
	public java.lang.Integer getRoomTypeId() {
		return getInt("room_type_id");
	}
	
	/**
	 * 年-月-日
	 */
	public void setDate(java.util.Date date) {
		set("date", date);
	}
	
	/**
	 * 年-月-日
	 */
	public java.util.Date getDate() {
		return getDate("date");
	}
	
	/**
	 * 售卖价格
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 售卖价格
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}
	
	/**
	 * 0正常 1删除
	 */
	public void setIsDel(java.lang.Integer isDel) {
		set("is_del", isDel);
	}
	
	/**
	 * 0正常 1删除
	 */
	public java.lang.Integer getIsDel() {
		return getInt("is_del");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 添加时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 添加时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 操作人ID
	 */
	public void setOperId(java.lang.Integer operId) {
		set("oper_id", operId);
	}
	
	/**
	 * 操作人ID
	 */
	public java.lang.Integer getOperId() {
		return getInt("oper_id");
	}
	
	/**
	 * 操作人
	 */
	public void setOperName(java.lang.String operName) {
		set("oper_name", operName);
	}
	
	/**
	 * 操作人
	 */
	public java.lang.String getOperName() {
		return getStr("oper_name");
	}
	
	/**
	 * 1：有房；0：满房/关房；100：:强制开房
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 1：有房；0：满房/关房；100：:强制开房
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 艺龙RoomId
	 */
	public void setElongRoomid(java.lang.String elongRoomid) {
		set("elong_RoomId", elongRoomid);
	}
	
	/**
	 * 艺龙RoomId
	 */
	public java.lang.String getElongRoomid() {
		return getStr("elong_RoomId");
	}
	
	/**
	 * 0没房， 是接口更新价态状态
	 */
	public void setEsStatus(java.lang.Integer esStatus) {
		set("es_status", esStatus);
	}
	
	/**
	 * 0没房， 是接口更新价态状态
	 */
	public java.lang.Integer getEsStatus() {
		return getInt("es_status");
	}
	
	/**
	 * 角色ID（2-业主，3-店长，4-员工）
	 */
	public void setEmployRoleId(java.lang.Integer employRoleId) {
		set("employ_role_id", employRoleId);
	}
	
	/**
	 * 角色ID（2-业主，3-店长，4-员工）
	 */
	public java.lang.Integer getEmployRoleId() {
		return getInt("employ_role_id");
	}
	
	/**
	 * 底价
	 */
	public void setCost(java.math.BigDecimal cost) {
		set("cost", cost);
	}
	
	/**
	 * 底价
	 */
	public java.math.BigDecimal getCost() {
		return get("cost");
	}
	
	/**
	 * 入住订单间夜
	 */
	public void setOrderRoomsSum(java.lang.Integer orderRoomsSum) {
		set("order_rooms_sum", orderRoomsSum);
	}
	
	/**
	 * 入住订单间夜
	 */
	public java.lang.Integer getOrderRoomsSum() {
		return getInt("order_rooms_sum");
	}
	
	/**
	 * 是否特殊日期
	 */
	public void setIsSpecialDay(java.lang.Boolean isSpecialDay) {
		set("is_special_day", isSpecialDay);
	}
	
	/**
	 * 是否特殊日期
	 */
	public java.lang.Boolean getIsSpecialDay() {
		return get("is_special_day");
	}
	
	/**
	 * 特殊日期酒店结算底价
	 */
	public void setSpecialCost(java.math.BigDecimal specialCost) {
		set("special_cost", specialCost);
	}
	
	/**
	 * 特殊日期酒店结算底价
	 */
	public java.math.BigDecimal getSpecialCost() {
		return get("special_cost");
	}
	
	/**
	 * 今日房量
	 */
	public void setTodayStock(java.lang.Integer todayStock) {
		set("today_stock", todayStock);
	}
	
	/**
	 * 今日房量
	 */
	public java.lang.Integer getTodayStock() {
		return getInt("today_stock");
	}
	
}

