package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 用户编号默认跟ID一样
	 */
	public void setUserCode(java.lang.String userCode) {
		set("user_code", userCode);
	}
	
	/**
	 * 用户编号默认跟ID一样
	 */
	public java.lang.String getUserCode() {
		return getStr("user_code");
	}
	
	/**
	 * 用户名称
	 */
	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}
	
	/**
	 * 用户名称
	 */
	public java.lang.String getUserName() {
		return getStr("user_name");
	}
	
	/**
	 * 密码
	 */
	public void setPasswd(java.lang.String passwd) {
		set("passwd", passwd);
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPasswd() {
		return getStr("passwd");
	}
	
	/**
	 * 部门编号
	 */
	public void setOrgId(java.lang.String orgId) {
		set("org_id", orgId);
	}
	
	/**
	 * 部门编号
	 */
	public java.lang.String getOrgId() {
		return getStr("org_id");
	}
	
	/**
	 * 职务
	 */
	public void setPost(java.lang.String post) {
		set("post", post);
	}
	
	/**
	 * 职务
	 */
	public java.lang.String getPost() {
		return getStr("post");
	}
	
	/**
	 * 1;男,0女
	 */
	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}
	
	/**
	 * 1;男,0女
	 */
	public java.lang.Integer getSex() {
		return getInt("sex");
	}
	
	/**
	 * 电话
	 */
	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}
	
	/**
	 * 电话
	 */
	public java.lang.String getTel() {
		return getStr("tel");
	}
	
	/**
	 * 手机号码
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 手机号码
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	/**
	 * EMAIL
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * EMAIL
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	/**
	 * 家庭地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	/**
	 * 家庭地址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	/**
	 * 允许登录
	 */
	public void setAllowLogin(java.lang.Integer allowLogin) {
		set("allow_login", allowLogin);
	}
	
	/**
	 * 允许登录
	 */
	public java.lang.Integer getAllowLogin() {
		return getInt("allow_login");
	}
	
	/**
	 * 删除操作（1：删除未审核）
	 */
	public void setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
	}
	
	/**
	 * 删除操作（1：删除未审核）
	 */
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	/**
	 * 允许登录时间或最后登录时间
	 */
	public void setAllowLoginTime(java.util.Date allowLoginTime) {
		set("allow_login_time", allowLoginTime);
	}
	
	/**
	 * 允许登录时间或最后登录时间
	 */
	public java.util.Date getAllowLoginTime() {
		return getDate("allow_login_time");
	}
	
	/**
	 * 登录错误次数
	 */
	public void setFailureNumber(java.lang.Integer failureNumber) {
		set("failure_number", failureNumber);
	}
	
	/**
	 * 登录错误次数
	 */
	public java.lang.Integer getFailureNumber() {
		return getInt("failure_number");
	}
	
	/**
	 * 用户主题切换
	 */
	public void setTheme(java.lang.String theme) {
		set("theme", theme);
	}
	
	/**
	 * 用户主题切换
	 */
	public java.lang.String getTheme() {
		return getStr("theme");
	}
	
}

