package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysRole<M extends BaseSysRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setDescript(java.lang.String descript) {
		set("descript", descript);
	}
	
	public java.lang.String getDescript() {
		return getStr("descript");
	}
	
	public void setIsStop(java.lang.Integer isStop) {
		set("is_stop", isStop);
	}
	
	public java.lang.Integer getIsStop() {
		return getInt("is_stop");
	}
	
	public void setOrgid(java.lang.String orgid) {
		set("orgid", orgid);
	}
	
	public java.lang.String getOrgid() {
		return getStr("orgid");
	}
	
	public void setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.String getParentId() {
		return getStr("parent_id");
	}
	
	public void setRoleCode(java.lang.String roleCode) {
		set("role_code", roleCode);
	}
	
	public java.lang.String getRoleCode() {
		return getStr("role_code");
	}
	
	public void setRoleName(java.lang.String roleName) {
		set("role_name", roleName);
	}
	
	public java.lang.String getRoleName() {
		return getStr("role_name");
	}
	
	public void setUserCode(java.lang.String userCode) {
		set("user_code", userCode);
	}
	
	public java.lang.String getUserCode() {
		return getStr("user_code");
	}
	
	public void setVisitView(java.lang.String visitView) {
		set("visit_view", visitView);
	}
	
	public java.lang.String getVisitView() {
		return getStr("visit_view");
	}
	
}

