package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEbookingRoomType<M extends BaseEbookingRoomType<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 酒店id
	 */
	public void setElongHotelId(java.lang.String elongHotelId) {
		set("elong_hotel_id", elongHotelId);
	}
	
	/**
	 * 酒店id
	 */
	public java.lang.String getElongHotelId() {
		return getStr("elong_hotel_id");
	}
	
	/**
	 * 房型名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 房型名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 床型0：大床 1：双床 2：大/双床 3：三床 4：一单一双 5：单人床 6：上下铺 7：通铺 8：榻榻米 9：水床 10：圆床 11：拼床 99：未知
	 */
	public void setBed(java.lang.String bed) {
		set("bed", bed);
	}
	
	/**
	 * 床型0：大床 1：双床 2：大/双床 3：三床 4：一单一双 5：单人床 6：上下铺 7：通铺 8：榻榻米 9：水床 10：圆床 11：拼床 99：未知
	 */
	public java.lang.String getBed() {
		return getStr("bed");
	}
	
	/**
	 * 床型0：大床 1：双床 2：大/双床 3：三床 4：一单一双 5：单人床 6：上下铺 7：通铺 8：榻榻米 9：水床 10：圆床 11：拼床 99：未知
	 */
	public void setBedType(java.lang.Integer bedType) {
		set("bed_type", bedType);
	}
	
	/**
	 * 床型0：大床 1：双床 2：大/双床 3：三床 4：一单一双 5：单人床 6：上下铺 7：通铺 8：榻榻米 9：水床 10：圆床 11：拼床 99：未知
	 */
	public java.lang.Integer getBedType() {
		return getInt("bed_type");
	}
	
	/**
	 * 宽带0无 ； 2免费 ； 3收费 ； 4 部分收费； 5部分有且收费 ； 6部分有且免费 ； 8未知
	 */
	public void setBroadband(java.lang.String broadband) {
		set("broadband", broadband);
	}
	
	/**
	 * 宽带0无 ； 2免费 ； 3收费 ； 4 部分收费； 5部分有且收费 ； 6部分有且免费 ； 8未知
	 */
	public java.lang.String getBroadband() {
		return getStr("broadband");
	}
	
	/**
	 * 售卖开关 1售卖，0停售
	 */
	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}
	
	/**
	 * 售卖开关 1售卖，0停售
	 */
	public java.lang.Boolean getStatus() {
		return get("status");
	}
	
	/**
	 * 房间数量
	 */
	public void setTotalCount(java.lang.Integer totalCount) {
		set("total_count", totalCount);
	}
	
	/**
	 * 房间数量
	 */
	public java.lang.Integer getTotalCount() {
		return getInt("total_count");
	}
	
	/**
	 * 其他属性
	 */
	public void setAttr(java.lang.String attr) {
		set("attr", attr);
	}
	
	/**
	 * 其他属性
	 */
	public java.lang.String getAttr() {
		return getStr("attr");
	}
	
	/**
	 * 0正常 1删除
	 */
	public void setIsDel(java.lang.Boolean isDel) {
		set("is_del", isDel);
	}
	
	/**
	 * 0正常 1删除
	 */
	public java.lang.Boolean getIsDel() {
		return get("is_del");
	}
	
	/**
	 * 软删除
	 */
	public void setDeleteTime(java.lang.Integer deleteTime) {
		set("delete_time", deleteTime);
	}
	
	/**
	 * 软删除
	 */
	public java.lang.Integer getDeleteTime() {
		return getInt("delete_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 楼层
	 */
	public void setFloor(java.lang.String floor) {
		set("floor", floor);
	}
	
	/**
	 * 楼层
	 */
	public java.lang.String getFloor() {
		return getStr("floor");
	}
	
	/**
	 * 面积
	 */
	public void setArea(java.lang.String area) {
		set("area", area);
	}
	
	/**
	 * 面积
	 */
	public java.lang.String getArea() {
		return getStr("area");
	}
	
	/**
	 * 可住人数
	 */
	public void setPerson(java.lang.Integer person) {
		set("person", person);
	}
	
	/**
	 * 可住人数
	 */
	public java.lang.Integer getPerson() {
		return getInt("person");
	}
	
	/**
	 * 是否有窗(0-无窗，2-有窗，1-部分有窗)
	 */
	public void setIsWindow(java.lang.String isWindow) {
		set("is_window", isWindow);
	}
	
	/**
	 * 是否有窗(0-无窗，2-有窗，1-部分有窗)
	 */
	public java.lang.String getIsWindow() {
		return getStr("is_window");
	}
	
	/**
	 * 是否可以吸烟
	 */
	public void setIsSmoke(java.lang.Integer isSmoke) {
		set("is_smoke", isSmoke);
	}
	
	/**
	 * 是否可以吸烟
	 */
	public java.lang.Integer getIsSmoke() {
		return getInt("is_smoke");
	}
	
	/**
	 * 艺龙房型ID
	 */
	public void setElongRoomTypeId(java.lang.String elongRoomTypeId) {
		set("elong_room_type_id", elongRoomTypeId);
	}
	
	/**
	 * 艺龙房型ID
	 */
	public java.lang.String getElongRoomTypeId() {
		return getStr("elong_room_type_id");
	}
	
	/**
	 * 床型描述
	 */
	public void setBedDesc(java.lang.String bedDesc) {
		set("bed_desc", bedDesc);
	}
	
	/**
	 * 床型描述
	 */
	public java.lang.String getBedDesc() {
		return getStr("bed_desc");
	}
	
	/**
	 * 房型代表图
	 */
	public void setImageUrl(java.lang.String imageUrl) {
		set("image_url", imageUrl);
	}
	
	/**
	 * 房型代表图
	 */
	public java.lang.String getImageUrl() {
		return getStr("image_url");
	}
	
	/**
	 * 库存总房量
	 */
	public void setStock(java.lang.Integer stock) {
		set("stock", stock);
	}
	
	/**
	 * 库存总房量
	 */
	public java.lang.Integer getStock() {
		return getInt("stock");
	}
	
	/**
	 * 艺龙RoomId
	 */
	public void setElongRoomid(java.lang.String elongRoomid) {
		set("elong_RoomId", elongRoomid);
	}
	
	/**
	 * 艺龙RoomId
	 */
	public java.lang.String getElongRoomid() {
		return getStr("elong_RoomId");
	}
	
	/**
	 * 角色ID（2-业主，3-店长，4-员工）
	 */
	public void setEmployRoleId(java.lang.Integer employRoleId) {
		set("employ_role_id", employRoleId);
	}
	
	/**
	 * 角色ID（2-业主，3-店长，4-员工）
	 */
	public java.lang.Integer getEmployRoleId() {
		return getInt("employ_role_id");
	}
	
	/**
	 * 房型类型：1-标准间2-双床房3-三人房4-单人间5-家庭房6-大床房7-四人间8-套房9-床位房10-公寓11-别墅12-房车13-帐篷14-小木屋15-工作室
	 */
	public void setRoomTypeStd(java.lang.Integer RoomTypeStd) {
		set("RoomTypeStd", RoomTypeStd);
	}
	
	/**
	 * 房型类型：1-标准间2-双床房3-三人房4-单人间5-家庭房6-大床房7-四人间8-套房9-床位房10-公寓11-别墅12-房车13-帐篷14-小木屋15-工作室
	 */
	public java.lang.Integer getRoomTypeStd() {
		return getInt("RoomTypeStd");
	}
	
	/**
	 * 0-不能加床1-可以加床
	 */
	public void setAddBed(java.lang.Integer AddBed) {
		set("AddBed", AddBed);
	}
	
	/**
	 * 0-不能加床1-可以加床
	 */
	public java.lang.Integer getAddBed() {
		return getInt("AddBed");
	}
	
	/**
	 * 加床费用
	 */
	public void setAddBedFee(java.math.BigDecimal AddBedFee) {
		set("AddBedFee", AddBedFee);
	}
	
	/**
	 * 加床费用
	 */
	public java.math.BigDecimal getAddBedFee() {
		return get("AddBedFee");
	}
	
	/**
	 * 1-独立卫浴,2-公共卫浴，0-未知
	 */
	public void setBath(java.lang.Integer Bath) {
		set("Bath", Bath);
	}
	
	/**
	 * 1-独立卫浴,2-公共卫浴，0-未知
	 */
	public java.lang.Integer getBath() {
		return getInt("Bath");
	}
	
	/**
	 * 床的总数
	 */
	public void setBedQuantityTotal(java.lang.Integer BedQuantityTotal) {
		set("BedQuantityTotal", BedQuantityTotal);
	}
	
	/**
	 * 床的总数
	 */
	public java.lang.Integer getBedQuantityTotal() {
		return getInt("BedQuantityTotal");
	}
	
	/**
	 * 无线宽带（0没有，1全部房间有且收费，2全部房间有且免费，3部分房间有且收费，4部分房间有且免费）
	 */
	public void setWirelessBroadnet(java.lang.Integer WirelessBroadnet) {
		set("WirelessBroadnet", WirelessBroadnet);
	}
	
	/**
	 * 无线宽带（0没有，1全部房间有且收费，2全部房间有且免费，3部分房间有且收费，4部分房间有且免费）
	 */
	public java.lang.Integer getWirelessBroadnet() {
		return getInt("WirelessBroadnet");
	}
	
	/**
	 * 有线宽带（0没有，1全部房间有且收费，2全部房间有且免费，3部分房间有且收费，4部分房间有且免费）
	 */
	public void setWiredBroadnet(java.lang.Integer WiredBroadnet) {
		set("WiredBroadnet", WiredBroadnet);
	}
	
	/**
	 * 有线宽带（0没有，1全部房间有且收费，2全部房间有且免费，3部分房间有且收费，4部分房间有且免费）
	 */
	public java.lang.Integer getWiredBroadnet() {
		return getInt("WiredBroadnet");
	}
	
	/**
	 * 是否艺龙房型(1-是，0-否)
	 */
	public void setIsElong(java.lang.Integer isElong) {
		set("is_elong", isElong);
	}
	
	/**
	 * 是否艺龙房型(1-是，0-否)
	 */
	public java.lang.Integer getIsElong() {
		return getInt("is_elong");
	}
	
	/**
	 * 床个数
	 */
	public void setBedQuantity(java.lang.Integer BedQuantity) {
		set("BedQuantity", BedQuantity);
	}
	
	/**
	 * 床个数
	 */
	public java.lang.Integer getBedQuantity() {
		return getInt("BedQuantity");
	}
	
	/**
	 * 床宽单位米
	 */
	public void setBedWidth(java.math.BigDecimal BedWidth) {
		set("BedWidth", BedWidth);
	}
	
	/**
	 * 床宽单位米
	 */
	public java.math.BigDecimal getBedWidth() {
		return get("BedWidth");
	}
	
	/**
	 * 1-双人床2-圆床3-水床4-榻榻米5-炕6-沙发床7-太空舱8-小型双人床9-大床10-特大床11-单人床12-胶囊床13-上下铺
	 */
	public void setChildBedType(java.lang.Integer ChildBedType) {
		set("ChildBedType", ChildBedType);
	}
	
	/**
	 * 1-双人床2-圆床3-水床4-榻榻米5-炕6-沙发床7-太空舱8-小型双人床9-大床10-特大床11-单人床12-胶囊床13-上下铺
	 */
	public java.lang.Integer getChildBedType() {
		return getInt("ChildBedType");
	}
	
	/**
	 * 房型描述
	 */
	public void setDescription(java.lang.String Description) {
		set("Description", Description);
	}
	
	/**
	 * 房型描述
	 */
	public java.lang.String getDescription() {
		return getStr("Description");
	}
	
	/**
	 * 房型图片
	 */
	public void setPictures(java.lang.String pictures) {
		set("pictures", pictures);
	}
	
	/**
	 * 房型图片
	 */
	public java.lang.String getPictures() {
		return getStr("pictures");
	}
	
	/**
	 * 当前可扣免房数量
	 */
	public void setExcludequantity(java.lang.Integer excludequantity) {
		set("excludequantity", excludequantity);
	}
	
	/**
	 * 当前可扣免房数量
	 */
	public java.lang.Integer getExcludequantity() {
		return getInt("excludequantity");
	}
	
	/**
	 * 是否设过免房
	 */
	public void setExistsexclude(java.lang.Integer existsexclude) {
		set("existsexclude", existsexclude);
	}
	
	/**
	 * 是否设过免房
	 */
	public java.lang.Integer getExistsexclude() {
		return getInt("existsexclude");
	}
	
}

