package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExcludeRoom<M extends BaseExcludeRoom<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setRoomid(java.lang.Integer roomid) {
		set("roomid", roomid);
	}
	
	public java.lang.Integer getRoomid() {
		return getInt("roomid");
	}
	
	/**
	 * 0正常 1删除
	 */
	public void setIsDel(java.lang.Boolean isDel) {
		set("is_del", isDel);
	}
	
	/**
	 * 0正常 1删除
	 */
	public java.lang.Boolean getIsDel() {
		return get("is_del");
	}
	
	/**
	 * 软删除
	 */
	public void setDeleteTime(java.lang.Integer deleteTime) {
		set("delete_time", deleteTime);
	}
	
	/**
	 * 软删除
	 */
	public java.lang.Integer getDeleteTime() {
		return getInt("delete_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.lang.Integer updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.lang.Integer getUpdateTime() {
		return getInt("update_time");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.lang.Integer createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.Integer getCreateTime() {
		return getInt("create_time");
	}
	
	/**
	 * 剩总量
	 */
	public void setExcludequantity(java.lang.Integer excludequantity) {
		set("excludequantity", excludequantity);
	}
	
	/**
	 * 剩总量
	 */
	public java.lang.Integer getExcludequantity() {
		return getInt("excludequantity");
	}
	
	/**
	 * 可免费数
	 */
	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}
	
	/**
	 * 可免费数
	 */
	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}
	
	public void setBak(java.lang.String bak) {
		set("bak", bak);
	}
	
	public java.lang.String getBak() {
		return getStr("bak");
	}
	
	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}
	
	public void setUserpid(java.lang.Integer userpid) {
		set("userpid", userpid);
	}
	
	public java.lang.Integer getUserpid() {
		return getInt("userpid");
	}
	
	/**
	 * 订单id
	 */
	public void setOrderid(java.lang.Integer orderid) {
		set("orderid", orderid);
	}
	
	/**
	 * 订单id
	 */
	public java.lang.Integer getOrderid() {
		return getInt("orderid");
	}
	
	/**
	 * 1是添加免房数量 2是来单扣的免房数量 3取消订单还原数量
	 */
	public void setClass(java.lang.Integer _class) {
		set("class", _class);
	}
	
	/**
	 * 1是添加免房数量 2是来单扣的免房数量 3取消订单还原数量
	 */
	public java.lang.Integer getDbClass() {
		return getInt("class");
	}
	
	/**
	 * Y-m-d 的形式，标识当天成过单
	 */
	public void setDate(java.lang.String date) {
		set("date", date);
	}
	
	/**
	 * Y-m-d 的形式，标识当天成过单
	 */
	public java.lang.String getDate() {
		return getStr("date");
	}
	
	public void setEid(java.lang.String eid) {
		set("eid", eid);
	}
	
	public java.lang.String getEid() {
		return getStr("eid");
	}
	
	public void setUnusedhotelid(java.lang.Integer unusedhotelid) {
		set("unusedhotelid", unusedhotelid);
	}
	
	public java.lang.Integer getUnusedhotelid() {
		return getInt("unusedhotelid");
	}
	
}

