package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoom<M extends BaseRoom<M>> extends Model<M> implements IBean {

	/**
	 * 自增主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 自增主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 艺龙酒店id
	 */
	public void setElongId(java.lang.Integer ElongId) {
		set("ElongId", ElongId);
	}
	
	/**
	 * 艺龙酒店id
	 */
	public java.lang.Integer getElongId() {
		return getInt("ElongId");
	}
	
	/**
	 * 高德id
	 */
	public void setGdId(java.lang.Long GdId) {
		set("GdId", GdId);
	}
	
	/**
	 * 高德id
	 */
	public java.lang.Long getGdId() {
		return getLong("GdId");
	}
	
	/**
	 * 房型ID
	 */
	public void setRoomID(java.lang.String RoomID) {
		set("RoomID", RoomID);
	}
	
	/**
	 * 房型ID
	 */
	public java.lang.String getRoomID() {
		return getStr("RoomID");
	}
	
	/**
	 * 房型中文名称
	 */
	public void setRoomName(java.lang.String RoomName) {
		set("RoomName", RoomName);
	}
	
	/**
	 * 房型中文名称
	 */
	public java.lang.String getRoomName() {
		return getStr("RoomName");
	}
	
	/**
	 * 房型面积
	 */
	public void setArea(java.lang.String Area) {
		set("Area", Area);
	}
	
	/**
	 * 房型面积
	 */
	public java.lang.String getArea() {
		return getStr("Area");
	}
	
	/**
	 * 楼层
	 */
	public void setFloor(java.lang.String Floor) {
		set("Floor", Floor);
	}
	
	/**
	 * 楼层
	 */
	public java.lang.String getFloor() {
		return getStr("Floor");
	}
	
	/**
	 * 床型中文名称
	 */
	public void setBedType(java.lang.String BedType) {
		set("BedType", BedType);
	}
	
	/**
	 * 床型中文名称
	 */
	public java.lang.String getBedType() {
		return getStr("BedType");
	}
	
	/**
	 * 房间最大入住人数(单人间或有单字的为1人，三人间的为3人，其他的默认2人；7表示6人以上)
	 */
	public void setCapacity(java.lang.Integer Capacity) {
		set("Capacity", Capacity);
	}
	
	/**
	 * 房间最大入住人数(单人间或有单字的为1人，三人间的为3人，其他的默认2人；7表示6人以上)
	 */
	public java.lang.Integer getCapacity() {
		return getInt("Capacity");
	}
	
}

