package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHotelsC<M extends BaseHotelsC<M>> extends Model<M> implements IBean {

	public void setElongHotelId(java.lang.String elongHotelId) {
		set("elong_hotel_id", elongHotelId);
	}
	
	public java.lang.String getElongHotelId() {
		return getStr("elong_hotel_id");
	}
	
	public void setCommissionRate(java.math.BigDecimal commissionRate) {
		set("commission_rate", commissionRate);
	}
	
	public java.math.BigDecimal getCommissionRate() {
		return get("commission_rate");
	}
	
}

