package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLcCtripHotelPriceLog<M extends BaseLcCtripHotelPriceLog<M>> extends Model<M> implements IBean {

	public void setHotelId(java.math.BigInteger hotelId) {
		set("hotel_id", hotelId);
	}
	
	public java.math.BigInteger getHotelId() {
		return get("hotel_id");
	}
	
	public void setUptime(java.util.Date uptime) {
		set("uptime", uptime);
	}
	
	public java.util.Date getUptime() {
		return getDate("uptime");
	}
	
	public void setUp(java.lang.Integer up) {
		set("up", up);
	}
	
	public java.lang.Integer getUp() {
		return getInt("up");
	}
	
}

