package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSession<M extends BaseSession<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 用户编号
	 */
	public void setUserCode(java.lang.String userCode) {
		set("user_code", userCode);
	}
	
	/**
	 * 用户编号
	 */
	public java.lang.String getUserCode() {
		return getStr("user_code");
	}
	
	/**
	 * 过期时间
	 */
	public void setExpiretTime(java.lang.Long expiretTime) {
		set("expiret_time", expiretTime);
	}
	
	/**
	 * 过期时间
	 */
	public java.lang.Long getExpiretTime() {
		return getLong("expiret_time");
	}
	
}

