package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEbookingPricePlan<M extends BaseEbookingPricePlan<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 酒店id
	 */
	public void setHotelId(java.lang.String hotelId) {
		set("hotel_id", hotelId);
	}
	
	/**
	 * 酒店id
	 */
	public java.lang.String getHotelId() {
		return getStr("hotel_id");
	}
	
	/**
	 * 对应房间类型id
	 */
	public void setRoomTypeId(java.lang.String roomTypeId) {
		set("room_type_id", roomTypeId);
	}
	
	/**
	 * 对应房间类型id
	 */
	public java.lang.String getRoomTypeId() {
		return getStr("room_type_id");
	}
	
	/**
	 * 计划名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 计划名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 计划说明
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 计划说明
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 支付方式 1现付 2预付
	 */
	public void setPayway(java.lang.Integer payway) {
		set("payway", payway);
	}
	
	/**
	 * 支付方式 1现付 2预付
	 */
	public java.lang.Integer getPayway() {
		return getInt("payway");
	}
	
	/**
	 * 0不包含 1分早餐 2分早餐。。。。。100不限
	 */
	public void setBreakfast(java.lang.Integer breakfast) {
		set("breakfast", breakfast);
	}
	
	/**
	 * 0不包含 1分早餐 2分早餐。。。。。100不限
	 */
	public java.lang.Integer getBreakfast() {
		return getInt("breakfast");
	}
	
	/**
	 * 0:正常；1：删除
	 */
	public void setIsDel(java.lang.Boolean isDel) {
		set("is_del", isDel);
	}
	
	/**
	 * 0:正常；1：删除
	 */
	public java.lang.Boolean getIsDel() {
		return get("is_del");
	}
	
	/**
	 * 软删除
	 */
	public void setDeleteTime(java.lang.Integer deleteTime) {
		set("delete_time", deleteTime);
	}
	
	/**
	 * 软删除
	 */
	public java.lang.Integer getDeleteTime() {
		return getInt("delete_time");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public void setWeekPrice(java.lang.String weekPrice) {
		set("week_price", weekPrice);
	}
	
	public java.lang.String getWeekPrice() {
		return getStr("week_price");
	}
	
	/**
	 * 0:下架；1：上架
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 0:下架；1：上架
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 提前多少天取消订单
	 */
	public void setAdvanceDay(java.lang.Integer advanceDay) {
		set("advance_day", advanceDay);
	}
	
	/**
	 * 提前多少天取消订单
	 */
	public java.lang.Integer getAdvanceDay() {
		return getInt("advance_day");
	}
	
	/**
	 * 具体时间
	 */
	public void setSpecificDate(java.sql.Time specificDate) {
		set("specific_date", specificDate);
	}
	
	/**
	 * 具体时间
	 */
	public java.sql.Time getSpecificDate() {
		return get("specific_date");
	}
	
	/**
	 * 0:不扣费；1:金额；2：比例；3：首晚房费; 4：全部房费
	 */
	public void setCutType(java.lang.Integer cutType) {
		set("cut_type", cutType);
	}
	
	/**
	 * 0:不扣费；1:金额；2：比例；3：首晚房费; 4：全部房费
	 */
	public java.lang.Integer getCutType() {
		return getInt("cut_type");
	}
	
	/**
	 * 扣费值
	 */
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	/**
	 * 扣费值
	 */
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}
	
	/**
	 * 1:可以取消；2：不可取消
	 */
	public void setIsCancel(java.lang.Integer isCancel) {
		set("is_cancel", isCancel);
	}
	
	/**
	 * 1:可以取消；2：不可取消
	 */
	public java.lang.Integer getIsCancel() {
		return getInt("is_cancel");
	}
	
	/**
	 * 操作人ID
	 */
	public void setOperId(java.lang.Integer operId) {
		set("oper_id", operId);
	}
	
	/**
	 * 操作人ID
	 */
	public java.lang.Integer getOperId() {
		return getInt("oper_id");
	}
	
	/**
	 * 操作人姓名
	 */
	public void setOperName(java.lang.String operName) {
		set("oper_name", operName);
	}
	
	/**
	 * 操作人姓名
	 */
	public java.lang.String getOperName() {
		return getStr("oper_name");
	}
	
	/**
	 * 艺龙RoomId
	 */
	public void setElongRoomid(java.lang.String elongRoomid) {
		set("elong_RoomId", elongRoomid);
	}
	
	/**
	 * 艺龙RoomId
	 */
	public java.lang.String getElongRoomid() {
		return getStr("elong_RoomId");
	}
	
	/**
	 * 角色ID（2-业主，3-店长，4-员工）
	 */
	public void setEmployRoleId(java.lang.Integer employRoleId) {
		set("employ_role_id", employRoleId);
	}
	
	/**
	 * 角色ID（2-业主，3-店长，4-员工）
	 */
	public java.lang.Integer getEmployRoleId() {
		return getInt("employ_role_id");
	}
	
	public void setYouzouHash(java.lang.String youzouHash) {
		set("youzou_hash", youzouHash);
	}
	
	public java.lang.String getYouzouHash() {
		return getStr("youzou_hash");
	}
	
	public void setElongHash(java.lang.String elongHash) {
		set("elong_hash", elongHash);
	}
	
	public java.lang.String getElongHash() {
		return getStr("elong_hash");
	}
	
	/**
	 * youzou商口id
	 */
	public void setYouzouGoodsid(java.lang.Integer youzouGoodsid) {
		set("youzou_goodsid", youzouGoodsid);
	}
	
	/**
	 * youzou商口id
	 */
	public java.lang.Integer getYouzouGoodsid() {
		return getInt("youzou_goodsid");
	}
	
	/**
	 * 酒店结算底价
	 */
	public void setCost(java.math.BigDecimal cost) {
		set("cost", cost);
	}
	
	/**
	 * 酒店结算底价
	 */
	public java.math.BigDecimal getCost() {
		return get("cost");
	}
	
	/**
	 * 酒店周末结算底价
	 */
	public void setWeekendCost(java.math.BigDecimal weekendCost) {
		set("weekend_cost", weekendCost);
	}
	
	/**
	 * 酒店周末结算底价
	 */
	public java.math.BigDecimal getWeekendCost() {
		return get("weekend_cost");
	}
	
}

