package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEbookingRoomStock<M extends BaseEbookingRoomStock<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 酒店主键
	 */
	public void setHotelId(java.lang.Integer hotelId) {
		set("hotel_id", hotelId);
	}
	
	/**
	 * 酒店主键
	 */
	public java.lang.Integer getHotelId() {
		return getInt("hotel_id");
	}
	
	/**
	 * 房型id
	 */
	public void setRoomTypeId(java.lang.Integer roomTypeId) {
		set("room_type_id", roomTypeId);
	}
	
	/**
	 * 房型id
	 */
	public java.lang.Integer getRoomTypeId() {
		return getInt("room_type_id");
	}
	
	/**
	 * 日期
	 */
	public void setDate(java.util.Date date) {
		set("date", date);
	}
	
	/**
	 * 日期
	 */
	public java.util.Date getDate() {
		return getDate("date");
	}
	
	/**
	 * 剩余房量
	 */
	public void setSurplusCount(java.lang.Integer surplusCount) {
		set("surplus_count", surplusCount);
	}
	
	/**
	 * 剩余房量
	 */
	public java.lang.Integer getSurplusCount() {
		return getInt("surplus_count");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 1正常 2删除
	 */
	public void setIsDel(java.lang.Integer isDel) {
		set("is_del", isDel);
	}
	
	/**
	 * 1正常 2删除
	 */
	public java.lang.Integer getIsDel() {
		return getInt("is_del");
	}
	
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 已售库存
	 */
	public void setSailCount(java.lang.Integer sailCount) {
		set("sail_count", sailCount);
	}
	
	/**
	 * 已售库存
	 */
	public java.lang.Integer getSailCount() {
		return getInt("sail_count");
	}
	
	/**
	 * 总库存
	 */
	public void setCount(java.lang.Integer count) {
		set("count", count);
	}
	
	/**
	 * 总库存
	 */
	public java.lang.Integer getCount() {
		return getInt("count");
	}
	
	/**
	 * 艺龙RoomId
	 */
	public void setElongRoomid(java.lang.String elongRoomid) {
		set("elong_RoomId", elongRoomid);
	}
	
	/**
	 * 艺龙RoomId
	 */
	public java.lang.String getElongRoomid() {
		return getStr("elong_RoomId");
	}
	
	/**
	 * 角色ID（2-业主，3-店长，4-员工）
	 */
	public void setEmployRoleId(java.lang.Integer employRoleId) {
		set("employ_role_id", employRoleId);
	}
	
	/**
	 * 角色ID（2-业主，3-店长，4-员工）
	 */
	public java.lang.Integer getEmployRoleId() {
		return getInt("employ_role_id");
	}
	
}

