package com.jinyan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataDictionary<M extends BaseDataDictionary<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 字典编号
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 字典编号
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}
	
	/**
	 * 字典名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 字典名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 排序
	 */
	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}
	
}

